# Generated by Django 4.0.4 on 2022-11-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='rain_No',
            new_name='train_No',
        ),
    ]
